QT += core gui openglwidgets

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    classes/atom.cpp \
    classes/orbit_camera.cpp \
    classes/parse_file.cpp \
    includes/glm/detail/glm.cpp \
    main.cpp \
    mainwindow.cpp \
    widgets/molecule_visualization_widget.cpp

HEADERS += \
    classes/atom.h \
    classes/orbit_camera.h \
    classes/parse_file.h \
    includes/glm/common.hpp \
    includes/glm/detail/_fixes.hpp \
    includes/glm/detail/_noise.hpp \
    includes/glm/detail/_swizzle.hpp \
    includes/glm/detail/_swizzle_func.hpp \
    includes/glm/detail/_vectorize.hpp \
    includes/glm/detail/compute_common.hpp \
    includes/glm/detail/compute_vector_decl.hpp \
    includes/glm/detail/compute_vector_relational.hpp \
    includes/glm/detail/func_common.inl \
    includes/glm/detail/func_common_simd.inl \
    includes/glm/detail/func_exponential.inl \
    includes/glm/detail/func_exponential_simd.inl \
    includes/glm/detail/func_geometric.inl \
    includes/glm/detail/func_geometric_simd.inl \
    includes/glm/detail/func_integer.inl \
    includes/glm/detail/func_integer_simd.inl \
    includes/glm/detail/func_matrix.inl \
    includes/glm/detail/func_matrix_simd.inl \
    includes/glm/detail/func_packing.inl \
    includes/glm/detail/func_packing_simd.inl \
    includes/glm/detail/func_trigonometric.inl \
    includes/glm/detail/func_trigonometric_simd.inl \
    includes/glm/detail/func_vector_relational.inl \
    includes/glm/detail/func_vector_relational_simd.inl \
    includes/glm/detail/qualifier.hpp \
    includes/glm/detail/setup.hpp \
    includes/glm/detail/type_float.hpp \
    includes/glm/detail/type_half.hpp \
    includes/glm/detail/type_half.inl \
    includes/glm/detail/type_mat2x2.hpp \
    includes/glm/detail/type_mat2x2.inl \
    includes/glm/detail/type_mat2x3.hpp \
    includes/glm/detail/type_mat2x3.inl \
    includes/glm/detail/type_mat2x4.hpp \
    includes/glm/detail/type_mat2x4.inl \
    includes/glm/detail/type_mat3x2.hpp \
    includes/glm/detail/type_mat3x2.inl \
    includes/glm/detail/type_mat3x3.hpp \
    includes/glm/detail/type_mat3x3.inl \
    includes/glm/detail/type_mat3x4.hpp \
    includes/glm/detail/type_mat3x4.inl \
    includes/glm/detail/type_mat4x2.hpp \
    includes/glm/detail/type_mat4x2.inl \
    includes/glm/detail/type_mat4x3.hpp \
    includes/glm/detail/type_mat4x3.inl \
    includes/glm/detail/type_mat4x4.hpp \
    includes/glm/detail/type_mat4x4.inl \
    includes/glm/detail/type_mat4x4_simd.inl \
    includes/glm/detail/type_quat.hpp \
    includes/glm/detail/type_quat.inl \
    includes/glm/detail/type_quat_simd.inl \
    includes/glm/detail/type_vec1.hpp \
    includes/glm/detail/type_vec1.inl \
    includes/glm/detail/type_vec2.hpp \
    includes/glm/detail/type_vec2.inl \
    includes/glm/detail/type_vec3.hpp \
    includes/glm/detail/type_vec3.inl \
    includes/glm/detail/type_vec4.hpp \
    includes/glm/detail/type_vec4.inl \
    includes/glm/detail/type_vec_simd.inl \
    includes/glm/exponential.hpp \
    includes/glm/ext.hpp \
    includes/glm/ext/_matrix_vectorize.hpp \
    includes/glm/ext/matrix_clip_space.hpp \
    includes/glm/ext/matrix_clip_space.inl \
    includes/glm/ext/matrix_common.hpp \
    includes/glm/ext/matrix_common.inl \
    includes/glm/ext/matrix_double2x2.hpp \
    includes/glm/ext/matrix_double2x2_precision.hpp \
    includes/glm/ext/matrix_double2x3.hpp \
    includes/glm/ext/matrix_double2x3_precision.hpp \
    includes/glm/ext/matrix_double2x4.hpp \
    includes/glm/ext/matrix_double2x4_precision.hpp \
    includes/glm/ext/matrix_double3x2.hpp \
    includes/glm/ext/matrix_double3x2_precision.hpp \
    includes/glm/ext/matrix_double3x3.hpp \
    includes/glm/ext/matrix_double3x3_precision.hpp \
    includes/glm/ext/matrix_double3x4.hpp \
    includes/glm/ext/matrix_double3x4_precision.hpp \
    includes/glm/ext/matrix_double4x2.hpp \
    includes/glm/ext/matrix_double4x2_precision.hpp \
    includes/glm/ext/matrix_double4x3.hpp \
    includes/glm/ext/matrix_double4x3_precision.hpp \
    includes/glm/ext/matrix_double4x4.hpp \
    includes/glm/ext/matrix_double4x4_precision.hpp \
    includes/glm/ext/matrix_float2x2.hpp \
    includes/glm/ext/matrix_float2x2_precision.hpp \
    includes/glm/ext/matrix_float2x3.hpp \
    includes/glm/ext/matrix_float2x3_precision.hpp \
    includes/glm/ext/matrix_float2x4.hpp \
    includes/glm/ext/matrix_float2x4_precision.hpp \
    includes/glm/ext/matrix_float3x2.hpp \
    includes/glm/ext/matrix_float3x2_precision.hpp \
    includes/glm/ext/matrix_float3x3.hpp \
    includes/glm/ext/matrix_float3x3_precision.hpp \
    includes/glm/ext/matrix_float3x4.hpp \
    includes/glm/ext/matrix_float3x4_precision.hpp \
    includes/glm/ext/matrix_float4x2.hpp \
    includes/glm/ext/matrix_float4x2_precision.hpp \
    includes/glm/ext/matrix_float4x3.hpp \
    includes/glm/ext/matrix_float4x3_precision.hpp \
    includes/glm/ext/matrix_float4x4.hpp \
    includes/glm/ext/matrix_float4x4_precision.hpp \
    includes/glm/ext/matrix_int2x2.hpp \
    includes/glm/ext/matrix_int2x2_sized.hpp \
    includes/glm/ext/matrix_int2x3.hpp \
    includes/glm/ext/matrix_int2x3_sized.hpp \
    includes/glm/ext/matrix_int2x4.hpp \
    includes/glm/ext/matrix_int2x4_sized.hpp \
    includes/glm/ext/matrix_int3x2.hpp \
    includes/glm/ext/matrix_int3x2_sized.hpp \
    includes/glm/ext/matrix_int3x3.hpp \
    includes/glm/ext/matrix_int3x3_sized.hpp \
    includes/glm/ext/matrix_int3x4.hpp \
    includes/glm/ext/matrix_int3x4_sized.hpp \
    includes/glm/ext/matrix_int4x2.hpp \
    includes/glm/ext/matrix_int4x2_sized.hpp \
    includes/glm/ext/matrix_int4x3.hpp \
    includes/glm/ext/matrix_int4x3_sized.hpp \
    includes/glm/ext/matrix_int4x4.hpp \
    includes/glm/ext/matrix_int4x4_sized.hpp \
    includes/glm/ext/matrix_integer.hpp \
    includes/glm/ext/matrix_integer.inl \
    includes/glm/ext/matrix_projection.hpp \
    includes/glm/ext/matrix_projection.inl \
    includes/glm/ext/matrix_relational.hpp \
    includes/glm/ext/matrix_relational.inl \
    includes/glm/ext/matrix_transform.hpp \
    includes/glm/ext/matrix_transform.inl \
    includes/glm/ext/matrix_uint2x2.hpp \
    includes/glm/ext/matrix_uint2x2_sized.hpp \
    includes/glm/ext/matrix_uint2x3.hpp \
    includes/glm/ext/matrix_uint2x3_sized.hpp \
    includes/glm/ext/matrix_uint2x4.hpp \
    includes/glm/ext/matrix_uint2x4_sized.hpp \
    includes/glm/ext/matrix_uint3x2.hpp \
    includes/glm/ext/matrix_uint3x2_sized.hpp \
    includes/glm/ext/matrix_uint3x3.hpp \
    includes/glm/ext/matrix_uint3x3_sized.hpp \
    includes/glm/ext/matrix_uint3x4.hpp \
    includes/glm/ext/matrix_uint3x4_sized.hpp \
    includes/glm/ext/matrix_uint4x2.hpp \
    includes/glm/ext/matrix_uint4x2_sized.hpp \
    includes/glm/ext/matrix_uint4x3.hpp \
    includes/glm/ext/matrix_uint4x3_sized.hpp \
    includes/glm/ext/matrix_uint4x4.hpp \
    includes/glm/ext/matrix_uint4x4_sized.hpp \
    includes/glm/ext/quaternion_common.hpp \
    includes/glm/ext/quaternion_common.inl \
    includes/glm/ext/quaternion_common_simd.inl \
    includes/glm/ext/quaternion_double.hpp \
    includes/glm/ext/quaternion_double_precision.hpp \
    includes/glm/ext/quaternion_exponential.hpp \
    includes/glm/ext/quaternion_exponential.inl \
    includes/glm/ext/quaternion_float.hpp \
    includes/glm/ext/quaternion_float_precision.hpp \
    includes/glm/ext/quaternion_geometric.hpp \
    includes/glm/ext/quaternion_geometric.inl \
    includes/glm/ext/quaternion_relational.hpp \
    includes/glm/ext/quaternion_relational.inl \
    includes/glm/ext/quaternion_transform.hpp \
    includes/glm/ext/quaternion_transform.inl \
    includes/glm/ext/quaternion_trigonometric.hpp \
    includes/glm/ext/quaternion_trigonometric.inl \
    includes/glm/ext/scalar_common.hpp \
    includes/glm/ext/scalar_common.inl \
    includes/glm/ext/scalar_constants.hpp \
    includes/glm/ext/scalar_constants.inl \
    includes/glm/ext/scalar_int_sized.hpp \
    includes/glm/ext/scalar_integer.hpp \
    includes/glm/ext/scalar_integer.inl \
    includes/glm/ext/scalar_packing.hpp \
    includes/glm/ext/scalar_packing.inl \
    includes/glm/ext/scalar_reciprocal.hpp \
    includes/glm/ext/scalar_reciprocal.inl \
    includes/glm/ext/scalar_relational.hpp \
    includes/glm/ext/scalar_relational.inl \
    includes/glm/ext/scalar_uint_sized.hpp \
    includes/glm/ext/scalar_ulp.hpp \
    includes/glm/ext/scalar_ulp.inl \
    includes/glm/ext/vector_bool1.hpp \
    includes/glm/ext/vector_bool1_precision.hpp \
    includes/glm/ext/vector_bool2.hpp \
    includes/glm/ext/vector_bool2_precision.hpp \
    includes/glm/ext/vector_bool3.hpp \
    includes/glm/ext/vector_bool3_precision.hpp \
    includes/glm/ext/vector_bool4.hpp \
    includes/glm/ext/vector_bool4_precision.hpp \
    includes/glm/ext/vector_common.hpp \
    includes/glm/ext/vector_common.inl \
    includes/glm/ext/vector_double1.hpp \
    includes/glm/ext/vector_double1_precision.hpp \
    includes/glm/ext/vector_double2.hpp \
    includes/glm/ext/vector_double2_precision.hpp \
    includes/glm/ext/vector_double3.hpp \
    includes/glm/ext/vector_double3_precision.hpp \
    includes/glm/ext/vector_double4.hpp \
    includes/glm/ext/vector_double4_precision.hpp \
    includes/glm/ext/vector_float1.hpp \
    includes/glm/ext/vector_float1_precision.hpp \
    includes/glm/ext/vector_float2.hpp \
    includes/glm/ext/vector_float2_precision.hpp \
    includes/glm/ext/vector_float3.hpp \
    includes/glm/ext/vector_float3_precision.hpp \
    includes/glm/ext/vector_float4.hpp \
    includes/glm/ext/vector_float4_precision.hpp \
    includes/glm/ext/vector_int1.hpp \
    includes/glm/ext/vector_int1_sized.hpp \
    includes/glm/ext/vector_int2.hpp \
    includes/glm/ext/vector_int2_sized.hpp \
    includes/glm/ext/vector_int3.hpp \
    includes/glm/ext/vector_int3_sized.hpp \
    includes/glm/ext/vector_int4.hpp \
    includes/glm/ext/vector_int4_sized.hpp \
    includes/glm/ext/vector_integer.hpp \
    includes/glm/ext/vector_integer.inl \
    includes/glm/ext/vector_packing.hpp \
    includes/glm/ext/vector_packing.inl \
    includes/glm/ext/vector_reciprocal.hpp \
    includes/glm/ext/vector_reciprocal.inl \
    includes/glm/ext/vector_relational.hpp \
    includes/glm/ext/vector_relational.inl \
    includes/glm/ext/vector_uint1.hpp \
    includes/glm/ext/vector_uint1_sized.hpp \
    includes/glm/ext/vector_uint2.hpp \
    includes/glm/ext/vector_uint2_sized.hpp \
    includes/glm/ext/vector_uint3.hpp \
    includes/glm/ext/vector_uint3_sized.hpp \
    includes/glm/ext/vector_uint4.hpp \
    includes/glm/ext/vector_uint4_sized.hpp \
    includes/glm/ext/vector_ulp.hpp \
    includes/glm/ext/vector_ulp.inl \
    includes/glm/fwd.hpp \
    includes/glm/geometric.hpp \
    includes/glm/glm.cppm \
    includes/glm/glm.hpp \
    includes/glm/gtc/bitfield.hpp \
    includes/glm/gtc/bitfield.inl \
    includes/glm/gtc/color_space.hpp \
    includes/glm/gtc/color_space.inl \
    includes/glm/gtc/constants.hpp \
    includes/glm/gtc/constants.inl \
    includes/glm/gtc/epsilon.hpp \
    includes/glm/gtc/epsilon.inl \
    includes/glm/gtc/integer.hpp \
    includes/glm/gtc/integer.inl \
    includes/glm/gtc/matrix_access.hpp \
    includes/glm/gtc/matrix_access.inl \
    includes/glm/gtc/matrix_integer.hpp \
    includes/glm/gtc/matrix_inverse.hpp \
    includes/glm/gtc/matrix_inverse.inl \
    includes/glm/gtc/matrix_transform.hpp \
    includes/glm/gtc/matrix_transform.inl \
    includes/glm/gtc/noise.hpp \
    includes/glm/gtc/noise.inl \
    includes/glm/gtc/packing.hpp \
    includes/glm/gtc/packing.inl \
    includes/glm/gtc/quaternion.hpp \
    includes/glm/gtc/quaternion.inl \
    includes/glm/gtc/quaternion_simd.inl \
    includes/glm/gtc/random.hpp \
    includes/glm/gtc/random.inl \
    includes/glm/gtc/reciprocal.hpp \
    includes/glm/gtc/round.hpp \
    includes/glm/gtc/round.inl \
    includes/glm/gtc/type_aligned.hpp \
    includes/glm/gtc/type_precision.hpp \
    includes/glm/gtc/type_precision.inl \
    includes/glm/gtc/type_ptr.hpp \
    includes/glm/gtc/type_ptr.inl \
    includes/glm/gtc/ulp.hpp \
    includes/glm/gtc/ulp.inl \
    includes/glm/gtc/vec1.hpp \
    includes/glm/gtx/associated_min_max.hpp \
    includes/glm/gtx/associated_min_max.inl \
    includes/glm/gtx/bit.hpp \
    includes/glm/gtx/bit.inl \
    includes/glm/gtx/closest_point.hpp \
    includes/glm/gtx/closest_point.inl \
    includes/glm/gtx/color_encoding.hpp \
    includes/glm/gtx/color_encoding.inl \
    includes/glm/gtx/color_space.hpp \
    includes/glm/gtx/color_space.inl \
    includes/glm/gtx/color_space_YCoCg.hpp \
    includes/glm/gtx/color_space_YCoCg.inl \
    includes/glm/gtx/common.hpp \
    includes/glm/gtx/common.inl \
    includes/glm/gtx/compatibility.hpp \
    includes/glm/gtx/compatibility.inl \
    includes/glm/gtx/component_wise.hpp \
    includes/glm/gtx/component_wise.inl \
    includes/glm/gtx/dual_quaternion.hpp \
    includes/glm/gtx/dual_quaternion.inl \
    includes/glm/gtx/easing.hpp \
    includes/glm/gtx/easing.inl \
    includes/glm/gtx/euler_angles.hpp \
    includes/glm/gtx/euler_angles.inl \
    includes/glm/gtx/extend.hpp \
    includes/glm/gtx/extend.inl \
    includes/glm/gtx/extended_min_max.hpp \
    includes/glm/gtx/extended_min_max.inl \
    includes/glm/gtx/exterior_product.hpp \
    includes/glm/gtx/exterior_product.inl \
    includes/glm/gtx/fast_exponential.hpp \
    includes/glm/gtx/fast_exponential.inl \
    includes/glm/gtx/fast_square_root.hpp \
    includes/glm/gtx/fast_square_root.inl \
    includes/glm/gtx/fast_trigonometry.hpp \
    includes/glm/gtx/fast_trigonometry.inl \
    includes/glm/gtx/float_normalize.inl \
    includes/glm/gtx/functions.hpp \
    includes/glm/gtx/functions.inl \
    includes/glm/gtx/gradient_paint.hpp \
    includes/glm/gtx/gradient_paint.inl \
    includes/glm/gtx/handed_coordinate_space.hpp \
    includes/glm/gtx/handed_coordinate_space.inl \
    includes/glm/gtx/hash.hpp \
    includes/glm/gtx/hash.inl \
    includes/glm/gtx/integer.hpp \
    includes/glm/gtx/integer.inl \
    includes/glm/gtx/intersect.hpp \
    includes/glm/gtx/intersect.inl \
    includes/glm/gtx/io.hpp \
    includes/glm/gtx/io.inl \
    includes/glm/gtx/iteration.hpp \
    includes/glm/gtx/iteration.inl \
    includes/glm/gtx/log_base.hpp \
    includes/glm/gtx/log_base.inl \
    includes/glm/gtx/matrix_cross_product.hpp \
    includes/glm/gtx/matrix_cross_product.inl \
    includes/glm/gtx/matrix_decompose.hpp \
    includes/glm/gtx/matrix_decompose.inl \
    includes/glm/gtx/matrix_factorisation.hpp \
    includes/glm/gtx/matrix_factorisation.inl \
    includes/glm/gtx/matrix_interpolation.hpp \
    includes/glm/gtx/matrix_interpolation.inl \
    includes/glm/gtx/matrix_major_storage.hpp \
    includes/glm/gtx/matrix_major_storage.inl \
    includes/glm/gtx/matrix_operation.hpp \
    includes/glm/gtx/matrix_operation.inl \
    includes/glm/gtx/matrix_query.hpp \
    includes/glm/gtx/matrix_query.inl \
    includes/glm/gtx/matrix_transform_2d.hpp \
    includes/glm/gtx/matrix_transform_2d.inl \
    includes/glm/gtx/mixed_product.hpp \
    includes/glm/gtx/mixed_product.inl \
    includes/glm/gtx/norm.hpp \
    includes/glm/gtx/norm.inl \
    includes/glm/gtx/normal.hpp \
    includes/glm/gtx/normal.inl \
    includes/glm/gtx/normalize_dot.hpp \
    includes/glm/gtx/normalize_dot.inl \
    includes/glm/gtx/number_precision.hpp \
    includes/glm/gtx/optimum_pow.hpp \
    includes/glm/gtx/optimum_pow.inl \
    includes/glm/gtx/orthonormalize.hpp \
    includes/glm/gtx/orthonormalize.inl \
    includes/glm/gtx/pca.hpp \
    includes/glm/gtx/pca.inl \
    includes/glm/gtx/perpendicular.hpp \
    includes/glm/gtx/perpendicular.inl \
    includes/glm/gtx/polar_coordinates.hpp \
    includes/glm/gtx/polar_coordinates.inl \
    includes/glm/gtx/projection.hpp \
    includes/glm/gtx/projection.inl \
    includes/glm/gtx/quaternion.hpp \
    includes/glm/gtx/quaternion.inl \
    includes/glm/gtx/range.hpp \
    includes/glm/gtx/raw_data.hpp \
    includes/glm/gtx/raw_data.inl \
    includes/glm/gtx/rotate_normalized_axis.hpp \
    includes/glm/gtx/rotate_normalized_axis.inl \
    includes/glm/gtx/rotate_vector.hpp \
    includes/glm/gtx/rotate_vector.inl \
    includes/glm/gtx/scalar_multiplication.hpp \
    includes/glm/gtx/scalar_relational.hpp \
    includes/glm/gtx/scalar_relational.inl \
    includes/glm/gtx/spline.hpp \
    includes/glm/gtx/spline.inl \
    includes/glm/gtx/std_based_type.hpp \
    includes/glm/gtx/std_based_type.inl \
    includes/glm/gtx/string_cast.hpp \
    includes/glm/gtx/string_cast.inl \
    includes/glm/gtx/structured_bindings.hpp \
    includes/glm/gtx/structured_bindings.inl \
    includes/glm/gtx/texture.hpp \
    includes/glm/gtx/texture.inl \
    includes/glm/gtx/transform.hpp \
    includes/glm/gtx/transform.inl \
    includes/glm/gtx/transform2.hpp \
    includes/glm/gtx/transform2.inl \
    includes/glm/gtx/type_aligned.hpp \
    includes/glm/gtx/type_aligned.inl \
    includes/glm/gtx/type_trait.hpp \
    includes/glm/gtx/type_trait.inl \
    includes/glm/gtx/vec_swizzle.hpp \
    includes/glm/gtx/vector_angle.hpp \
    includes/glm/gtx/vector_angle.inl \
    includes/glm/gtx/vector_query.hpp \
    includes/glm/gtx/vector_query.inl \
    includes/glm/gtx/wrap.hpp \
    includes/glm/gtx/wrap.inl \
    includes/glm/integer.hpp \
    includes/glm/mat2x2.hpp \
    includes/glm/mat2x3.hpp \
    includes/glm/mat2x4.hpp \
    includes/glm/mat3x2.hpp \
    includes/glm/mat3x3.hpp \
    includes/glm/mat3x4.hpp \
    includes/glm/mat4x2.hpp \
    includes/glm/mat4x3.hpp \
    includes/glm/mat4x4.hpp \
    includes/glm/matrix.hpp \
    includes/glm/packing.hpp \
    includes/glm/simd/common.h \
    includes/glm/simd/exponential.h \
    includes/glm/simd/geometric.h \
    includes/glm/simd/integer.h \
    includes/glm/simd/matrix.h \
    includes/glm/simd/neon.h \
    includes/glm/simd/packing.h \
    includes/glm/simd/platform.h \
    includes/glm/simd/trigonometric.h \
    includes/glm/simd/vector_relational.h \
    includes/glm/trigonometric.hpp \
    includes/glm/vec2.hpp \
    includes/glm/vec3.hpp \
    includes/glm/vec4.hpp \
    includes/glm/vector_relational.hpp \
    mainwindow.h \
    widgets/molecule_visualization_widget.h

FORMS += \
    mainwindow.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    includes/glm/CMakeLists.txt \
    shaders/testShader.vert \
    shaders/testShader2.fsh

RESOURCES += \
    shaders.qrc
